name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: npm ci

      # Build and publish core package
      - name: Build core
        working-directory: packages/core
        run: npm run build
      - name: Publish core
        working-directory: packages/core
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # Build and publish angular package
      - name: Build angular
        working-directory: packages/angular
        run: npm run build
      - name: Publish angular
        working-directory: packages/angular/dist
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # Build and publish react package
      - name: Build react
        working-directory: packages/react
        run: npm run build
      - name: Publish react
        working-directory: packages/react
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
